# Generated by Django 5.0.3 on 2024-04-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_book',
            new_name='add_books',
        ),
    ]
