# Generated by Django 5.0.3 on 2024-04-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_add_book_add_books'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='add_books',
            table='add_books',
        ),
    ]
