# Generated by Django 5.0.3 on 2024-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_add_books_count_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='add_books',
            name='count',
            field=models.IntegerField(),
        ),
    ]
